site_name: My Docs
site_url: https://tbarol.github.io/book1 # 網站位置
repo_url: https://github.com/tbarol/book1 # Github Repository位置，用於content.action.view設定
edit_uri: edit/main/docs/ # Github Repository編輯位置，用於content.action.edit設定

# Theme
theme:
  name: material # 使用material佈景主題
  language: zh-TW # 語系設定為繁體中文-台灣
  custom_dir: overrides # 定義複寫佈景主題的元件資料夾
  features:
    - search.suggest # 輸入搜尋字元時會依據打的字元顯示下一個可能的字元
    - search.highlight # 是否要將搜尋的字元以高亮方式凸顯
    - navigation.tabs # 於上方加入導航列並新增top-section內容
    - navigation.top # 顯示back-to-top按鈕
    - navigation.indexes # 當資料夾內僅有一個檔案時就直接顯示該檔案而不是資料夾->檔案
    - toc.integrate # 文章內容右側導航整併到左側文章導航內
    - content.action.edit # 顯示Github檢視連結在導覽列
    - content.action.view # 顯示Github編輯連結在導覽列

#Plugins
plugins:
  - search: # 搜尋插件，在沒有設定plugin情況下預設會啟用，但若有設定的話要手動加入否則不會啟用
      enable: true
      separator: '[\s\u200b\-]' # 繁體中文分隔方式（空白或沒有寬度的空白或連字符-）
  - blog: # 部落格插件
      enabled: true
      post_readtime: true # 是否依據字數計算預計閱讀時間並顯示
      archive: false # 是否顯示存檔頁面
      post_url_format: "{file}" # 設定blog post的url格式，預設為{date}/{slug}，故會加上日期，故若要在該篇文章引用同目錄其他元素時會有問題
      pagination_per_page: 1
  - git-revision-date-localized: # 跟蹤文章git提交日期，並可設定顯示於文章底部
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
      enabled: true

# Markdown Extensions
markdown_extensions:
  - attr_list # 允許增加mardown語法的HTML屬性或css class功能
  - md_in_html # 啟用在markdown內使用html語法功能
  - customblocks # # 可以使用:::來建立<div>標籤
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji: # 啟用內建emojis功能
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: "#" # 於標題右側新增錨點符號
      slugify: !!python/object/apply:pymdownx.slugs.slugify #轉換slug為HTML相容的文字，沒有設定的話toc產生的連結會無法顯示
        kwds:
          case: lower
# Custom styles and scripts
extra_css: # 自定義的CSS檔案
  - assets/stylesheets/extra.css
extra_javascript: # 自定義的javascript
  - assets/javascripts/extra.js